# More Python Basics

*This section uses content from the [Python section](https://melaniewalsh.github.io/Intro-Cultural-Analytics/02-Python/00-Python.html#) of Melanie Walsh's Introduction to Cultural Analytics & Python.*

The purpose of this notebook is to give you a stronger, more complete foundation for "vanilla" (built-in) Python by discussing loops, as well as to introduce the NumPy library. **The goal of this lab is to give you the tools you need to start building robust functions which can make useful calculations on large datasets.**

To that end, we'll cover the following:

1. More Python Basics
    - Loops
    - Generator Iterators
2. NumPy
    - NumPy Arrays
    - Array Operations

## Loops

Python provides two different types of loop: the `for` loop, and the `while` loop. The `for` loop iterates a block of code through the elements of some iterable (i.e., list-like) object, whereas the `while` loop executes a block of code as long as some condition is met. In other words, `for` loops are best suited for *finite* (definite) iteration, and `while` loops are best suited for *potentially infinite* (indefinite) iteration. For our purposes, **every loop should be finite**, so practically, any `while` loop can (and often should) be converted into a `for` loop.

We will introduce both here, but since `while` loops can sometimes result in infinite loops, often causing the computer to freeze up, our focus in this class will be on `for` loops.

### `while` loops

First, we'll take  a look at the `while` loop.

In [81]:
numbers = [1, "two", 3]

# start with `while`, the condition to be met, and then the block of code
while len(numbers) < 10:
    new_number = numbers[-1] + 1
    numbers.append(new_number)

numbers

[1, 'two', 3, 4, 5, 6, 7, 8, 9, 10]

**<span style='color:red;'>CAUTION:</span>** Do your best to **avoid using `while` loops at all**; try to convert them into a `for` loop (below) if possible.

`while` loops should only be *considered* for the following cases:
* infinite looping, where there might not ever be an end (mostly in software engineering)
* situations where the object being iterated through changes with each loop.

The latter of these is more common, but even then a `for` loop may still do the job.

### `for` loops

Again, a `for` loop will execute a block of code for each item in a list-like object. On the first line, we type the English word `for`, a new variable name for each item in the list, the English word `in`, the name of the list-like object, and then a colon `:`. All instructions for a `for` loop must be indented.

In [82]:
# suppose we want to print the odd numbers in `numbers` that are 5 or less
for number in numbers:
    # we can "skip" values using continue
    if number == "two":
        continue
    
    # remember what the `%` symbol does
    elif number % 2 == 1:
        print(f"{number} is an odd number.")
    
    # `break` completely stops the looping process
    elif number > 5:
        break

1 is an odd number.
3 is an odd number.
5 is an odd number.


* In the same way that variables (in general) should be descriptively named, the iterating variable of for-loops (between `for` and `in`) should be descriptive of what is held behind it.
* As it is usually difficult to determine what is going on, print statements help to "debug" the contents of variables as you go. **Use looped print statements sparingly!**

## Generator Iterators

In Python, an **iterable** is an object *containing* one or more data elements that a `for` loop can iterate over. For example, lists, tuples, dictionaries, and sets are all iterable objects. They provide multiple elements of data that you can iterate over.

However, consider two alternate scenarios:

1. We do not know all the elements to be iterated over, but we know how they are generated.
2. We know the elements to be iterated over, but we do not want them taking up memory until it is their "turn".

In either of these cases, we can use the Python [generator](https://realpython.com/introduction-to-python-generators/) iterator to 'stream' elements to iterate over.

Three common built-in Python generators are `range()`, `enumerate()`, and `zip()`.

### `range`

`range()` generates numbers in a sequence, from `(start, stop, step)`.

In [83]:
# on it's own, an iterator is just a function
range(10)

range(0, 10)

In [84]:
# by default, the first value will be 0, and step is 1
for i in range(3):
    print(i)

0
1
2


In [85]:
# we can iterate from 2 to 20, by step size 3
for i in range(2, 20, 3):
    print(i)

2
5
8
11
14
17


In [86]:
# we can even go backwards
for i in range(5, 1, -1):
    print(i)

5
4
3
2


### `enumerate`

If we are working with a defined iterable (like a list), but we also want to log the index of each element as we iterate over it, we can use `enumerate`.

In [87]:
names = ['astrid', 'jamaal', 'timo', 'hyewon']

# notice the order of `i` and `element` here
for i, element in enumerate(names):
    print(f"index: {i} ... element: {element}")

index: 0 ... element: astrid
index: 1 ... element: jamaal
index: 2 ... element: timo
index: 3 ... element: hyewon


### `zip`

Suppose we have two different iterables that we would like to combine into a list of tuples (or a dictionary).

In [88]:
keys = ["a", "b", "c"]
values = [1, 2, 3]

kv_dict = {}
kv_list = []

for k, v in zip(keys, values):
    kv_dict[k] = v
    kv_list.append((k, v))

In [89]:
kv_dict

{'a': 1, 'b': 2, 'c': 3}

In [90]:
kv_list

[('a', 1), ('b', 2), ('c', 3)]

In [91]:
# alternatively, we could use list/dictionary comprehensions
{k:v for k, v in zip(keys, values)}

{'a': 1, 'b': 2, 'c': 3}

### EXERCISE

The Fibonacci Series starts with 0 and 1. Each of the following numbers are the sum of the previous two numbers in the series. So, the first element is 0, the next element is 1, the next is 1, and the next is 2, and so on.

Write a function which *prints* the following, given a number `n`:

    Fibonacci 1 = 0
    Fibonacci 2 = 1
    Fibonacci 3 = 1
    ...
    Fibonacci n = ?

In [92]:
# your code here

# Intro to NumPy

*This is a summarized version of [NumPy's absolute beginners tutorial](https://numpy.org/doc/stable/user/absolute_beginners.html). Each sub-section title here links to its corresponding section in the tutorial.*

[NumPy](https://numpy.org/doc/stable/user/absolute_beginners.html) (Numerical Python) is an enormous open source Python library that is *easily* the universal standard for working with numerical data in Python. Its users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. NumPy improves on numerical programming in Python by introducing optimized low-level programming, and a library of high-level mathematical functions that operate on arrays and matrices.

You should be able to install NumPy into your conda environment for this course using `conda install numpy`.

In [93]:
import numpy as np

## [NumPy Arrays](https://numpy.org/doc/stable/user/absolute_beginners.html#what-is-an-array)

The NumPy n-dimensional array (`ndarray`) is the central data structure of the NumPy library. We can think of it roughly as a vector (with 1-dimension) or a matrix (with 2-dimensions), but it might be better to think of it as a "[tensor](https://www.kdnuggets.com/2018/05/wtf-tensor.html)" (with 3 or more, n-dimensions). NumPy arrays are homogeneous, i.e., the data type is consistent across all elements (this allows for optimized calculations). The `shape` of the array is a tuple of integers giving the size of the array along each dimension.

Note: NumPy is *vast* and has capabilities reaching far beyond what is included in this notebook. Again, **this is just an introduction to NumPy.**

In [94]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

In [95]:
# `.ndim` gives us the number of dimensions of our array
a.ndim

2

In [96]:
# `shape` gives the length of each dimension
a.shape

(2, 3)

In [97]:
# `size` is the number of elements in the array
a.size

6

Each dimension is called an **axis**, working your way from "inside" to "outside". E.g., in `a`, the rows are `axis 0`, and the columns are `axis 1`.

### [Building Arrays](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-a-basic-array)

There are many different ways to build arrays, but a few interesting ones are using the `arange` and `linspace` functions.

In [98]:
# arange is similar the `range` we've seen above
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [99]:
# linspace creates evenly spaced elements in an array
np.linspace(0, 5, num=11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [100]:
# convert a 1-d array to a 2-d array by adding an axis
np.arange(1, 10, 2)[:, np.newaxis]

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [101]:
# using `reshape` in this way is another way to add an axis
a = np.arange(3, 10, 2).reshape(-1, 1)
b = np.arange(4, 20, 4).reshape(-1, 1)

# concatenate is one way to merge arrays together
c = np.concatenate((a, b), axis=1)
c

array([[ 3,  4],
       [ 5,  8],
       [ 7, 12],
       [ 9, 16]])

In [102]:
# another example of reshaping
c.reshape(2, 4)

array([[ 3,  4,  5,  8],
       [ 7, 12,  9, 16]])

In [103]:
# we can "vertically" stack using vstack
a = np.array([3,  4,  5,  8])
b = np.array([7, 12,  9, 16])

np.vstack((a, b))

array([[ 3,  4,  5,  8],
       [ 7, 12,  9, 16]])

In [104]:
# or we could "horizontally" stack using hstack
a = np.array([3,  4,  5,  8])[:, np.newaxis]
b = np.array([7, 12,  9, 16])[:, np.newaxis]

np.hstack((a, b))

array([[ 3,  7],
       [ 4, 12],
       [ 5,  9],
       [ 8, 16]])

You can also [flatten](https://numpy.org/doc/stable/user/absolute_beginners.html#reshaping-and-flattening-multidimensional-arrays) arrays, which is a slightly different take on "reshaping". Here, we reduce the values of a multi-dimensional array into a flat, 1-D array.

In [105]:
x = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### [Indexing and Slicing](https://numpy.org/doc/stable/user/absolute_beginners.html#indexing-and-slicing)

There are several ways to extract "slices" of an array. The most basic mirrors how we'd slice a list (i.e., using `start:stop:step` syntax).

In [106]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[2:9:2]

array([3, 5, 7, 9])

We can also use boolean (True/False) filtering based on logical conditions. In NumPy, the **and** operator is `&`, and the **or** operator is `|`.

In [107]:
a = np.array([[1 , 2,  3,  4], 
              [5,  6,  7,  8], 
              [9, 10, 11, 12]])

mask = (a == 1) | (a > 5)
mask

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [108]:
a[mask]

array([ 1,  6,  7,  8,  9, 10, 11, 12])

Here, `np.where` returns values based on a condition, and we can use the `np.nan` (Not A Number, or "Null") value to represent missing values.

In [109]:
np.where(mask, a, np.nan)

array([[ 1., nan, nan, nan],
       [nan,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

We can also use the `[:]` notation to extract different kinds of slices.

In [110]:
# first "vector" (i.e., the first row)
a[0]

array([1, 2, 3, 4])

In [111]:
# the second value for each vector, think of `:` as all appropriate values
a[:, 1]

array([ 2,  6, 10])

In [112]:
# using [:] notation to get vertical column
a[:, 1:2]

array([[ 2],
       [ 6],
       [10]])

<span style='color:red;'>**Important Note on Slicing:**</span> Slices of arrays are *references* to the original array. **If you need to extract a permanently "independent" slice of an array, you need to `copy` it.**

In [113]:
a = np.array([[1 , 2,  3,  4], 
              [5,  6,  7,  8]])

# a copy to check later
a_copy = a.copy()

# here, we "extract" (refer to) a slice of `a`
a_slice = a[:, :2]
a_slice

array([[1, 2],
       [5, 6]])

In [114]:
# here, we amend (mutate) that slice
a_slice[0, :] = np.array([9, 9])
a_slice

array([[9, 9],
       [5, 6]])

In [115]:
# we have then updated the original array, too
a

array([[9, 9, 3, 4],
       [5, 6, 7, 8]])

In [116]:
a_copy

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### [Random Generation](https://numpy.org/doc/stable/user/absolute_beginners.html#generating-random-numbers)

NumPy also has the capability to generate random numbers from various probability distributions.

In [117]:
data = np.random.uniform(size=(2, 3))
data

array([[0.80925094, 0.69957871, 0.93601926],
       [0.08700374, 0.35425194, 0.93114611]])

In [118]:
# including a random seed ensures the "same random" generations with each run
gen = np.random.default_rng(seed=33)
gen.normal(loc=5, scale=1, size=(3, 2))

array([[5.39836997, 4.43717666],
       [5.58883494, 5.0421181 ],
       [3.42909948, 6.00165475]])

In [119]:
# the seed no longer applies when run alone
gen.normal(loc=5, scale=1, size=(3, 2))

array([[4.90212381, 5.61980221],
       [6.83683215, 5.26842997],
       [3.92553132, 4.31902103]])

## Array Operations

NumPy provides all the standard mathematical operations you'd expect, but the difference now is that these operations are extremely fast, and they operate in a "vectorized" fashion. This can happen in three ways: element-wise, using what is called "broadcasting", or using standard mathematical matrix operations. We can also calculate aggregate values such as mean or minimum, etc.

### [Element-wise Operations](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)

In [120]:
# we can create an array of only ones
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [121]:
# and we can also reshape an arange
a = np.arange(2, 18, 2).reshape((2, 4))
a

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [122]:
ones + a

array([[ 3.,  5.,  7.,  9.],
       [11., 13., 15., 17.]])

In [123]:
ones / a

array([[0.5       , 0.25      , 0.16666667, 0.125     ],
       [0.1       , 0.08333333, 0.07142857, 0.0625    ]])

### [Broadcasting](https://numpy.org/doc/stable/user/absolute_beginners.html#broadcasting)

When [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) an operation between two arrays (with potentially different shapes), NumPy first compares their shapes element-wise, starting with the trailing (i.e. rightmost) dimension, and working its way left. Two dimensions are compatible when (a) they are equal, or (b) one of them is 1.

```
Compatible:
(4, 5, 2)
   (5, 1)             First, 1 works. Then, 5 = 5.

Not compatible:
(100, 4)
  (5, 2)             First, 4 ≠ 2 and neither are 1.
```

In [124]:
a = np.array([[1, 2],
              [4, 5],
              [7, 8]])
               
b = np.array([[3], 
              [2], 
              [1]])

In [125]:
# Notice how multiplying by `b` is broadcast "across" `a`
print(f"a shape: {a.shape}")
print(f"b shape: {b.shape}")
a * b

a shape: (3, 2)
b shape: (3, 1)


array([[ 3,  6],
       [ 8, 10],
       [ 7,  8]])

In [126]:
# the same happens with scalars
4 * b

array([[12],
       [ 8],
       [ 4]])

In [127]:
# we an also broadcast across 2+ axes
c = np.array([1, 2, 3])

b * c

array([[3, 6, 9],
       [2, 4, 6],
       [1, 2, 3]])

### Matrix Arithmetic

Any array is essentially a matrix of values, and NumPy provides the standard matrix and vector operations. Here are just a few examples.

In [128]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

b = np.array([[9, 8, 7],
              [6, 5, 4]])

In [129]:
# the @ symbol represents matrix multiplication
a @ b

array([[21, 18, 15],
       [51, 44, 37],
       [81, 70, 59]])

In [130]:
# np.dot works too
np.dot(a, b)

array([[21, 18, 15],
       [51, 44, 37],
       [81, 70, 59]])

In [131]:
# .T calculates the transpose (not for single rows/columns)
a.T

array([[1, 3, 5],
       [2, 4, 6]])

### [Aggregation](https://numpy.org/doc/stable/user/absolute_beginners.html#more-useful-array-operations)

Often, you'll want to calculate aggregate functions (e.g., mean, minimum, etc.) for a whole array, or for just rows/columns (or some other axis).

In [132]:
a = np.array([[ 3,  6,  9, 12, 15],
              [ 4,  8, 12, 16, 20]])

In [133]:
# we can calculate a minimum for all the data
a.min()

3

In [134]:
# or, just across an axis (here, across columns for each row)
a.min(axis=1)

array([3, 4])

In [135]:
a.mean(axis=0)

array([ 3.5,  7. , 10.5, 14. , 17.5])

In [136]:
a.sum(axis=1)

array([45, 60])

Given a vector of weights, NumPy can also calculate a weighted average.

In [137]:
w = np.array([1, 4, 1, 2, 5])

In [138]:
np.average(a, axis=1, weights=w).reshape(-1, 1)

array([[10.38461538],
       [13.84615385]])

The [unique](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-get-unique-items-and-counts) function is helpful to find out the distinct values in a vector or tensor.

In [139]:
a = np.array([[11, 11, 12, 13, 14, 16, 17, 11, 13, 11, 14, 18, 10, 14]])

np.unique(a)

array([10, 11, 12, 13, 14, 16, 17, 18])

# Exercises

For these exercises, **do not import any libraries other than `numpy`**. You should be able to complete everything in this notebook with just the imports above.

## Exercise 1

In this exercise, we will determine the *indices* of particular values of an array (e.g., minimum, sorted, etc.) using `argmin`, `argmax`, and `argsort` (see the documentation, e.g., [argmin](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html)).

#### Question 1

Suppose we have five students, `s = np.array(['Hannah', 'Astrid', 'Abdul', 'Mauve', 'Jung'])`, and test scores for each student, `t = np.array([99, 71, 85, 62, 91])`, respectively.

In [140]:
s = np.array(['Hannah', 'Astrid', 'Abdul', 'Mauve', 'Jung'])
t = np.array([99, 71, 85, 62, 91])

#### Question 2

Given `s` and `t`, how can we calculate the name of the student with the lowest score using one line? What about the highest?

In [141]:
# your code here
s = np.array(['Hannah', 'Astrid', 'Abdul', 'Mauve', 'Jung'])
t = np.array([99, 71, 85, 62, 91])
student_with_lowest_score=s[np.argmin(t)]

In [142]:
# your code here
s = np.array(['Hannah', 'Astrid', 'Abdul', 'Mauve', 'Jung'])
t = np.array([99, 71, 85, 62, 91])
student_with_lowest_score=s[np.argmin(t)]

In [143]:
# your code here
student_with_lowest_score=s[np.argmin(t)]

In [144]:
# your code here
student_with_highest_score=s[np.argmax(t)]

#### Question 3

Given `s` and `t`, how can we calculate the name of the student with the second highest score using one line?

In [145]:
# your code here
second_highest_score=s[np.argsort(t)[-2]]

In [146]:
# your code here
s = np.array(['Hannah', 'Astrid', 'Abdul', 'Mauve', 'Jung'])
t = np.array([99, 71, 85, 62, 91])
second_highest_score=s[np.argsort(t)[-2]]

#### Question 4

Write the line of code that will list the names of students in *descending* order of test score (i.e., a list of names, with associated scores in order from highest to lowest).

In [147]:
# your code here
descending_scores=s[np.argsort(t)[::-1]]

## Exercise 2

Repeat Exercise 1 but only use loops or list comprehensions.

In [2]:
#### Question 2


##Given `s` and `t`, how can we calculate the name of the student with the lowest score using one line? 

s0 = ['Hannah', 'Astrid', 'Abdul', 'Mauve', 'Jung']
t0 = [99, 71, 85, 62, 91]
st_dict={}
for s,t in zip(s0,t0):
    st_dict[s]=t


student_with_lowest_score=min(st_dict,key=st_dict.get)

#What about the highest?

student_with_highest_score=max(st_dict,key=st_dict.get)
student_with_highest_score


'Hannah'

In [149]:
#### Question 3

##Given `s` and `t`, how can we calculate the name of the student with the second highest score using one line?
student_with_highest_score=max(st_dict,key=st_dict.get)
del st_dict[student_with_highest_score]
student_with_second_highest_score=max(st_dict,key=st_dict.get)

In [150]:
#### Question 4
####keep for more help https://realpython.com/iterate-through-dictionary-python/#traversing-a-dictionary-in-sorted-and-reverse-order

####Write the line of code that will list the names of students in *descending* order of test score (i.e., a list of names, with associated scores in order from highest to lowest).


s0 = ['Hannah', 'Astrid', 'Abdul', 'Mauve', 'Jung']
t0 = [99, 71, 85, 62, 91]
st_dict={}
for s,t in zip(s0,t0):
    st_dict[s]=t
descending_scores=[student for student, score in sorted(st_dict.items(),key=lambda x: x[1], reverse=True)]
print(descending_scores)

['Hannah', 'Jung', 'Abdul', 'Astrid', 'Mauve']


## (Optional) Exercise 3

- Let `s` be a 1-D boolean (True/False) NumPy array where each element represents a student, and each value is an indicator for whether a student was caught texting in class.
- Let `d` be 1-D numeric array where each element represents an instructor, and each value is the number of points removed from a student's grade if they are caught texting in class.

Write a function which takes in `s` and `d`, and returns an array with a row for each instructor, and a column for each student. The values should be the number of points removed for each student-instructor combination.

For example,

```python
s = np.array([True, False, False, True, True])
d = np.array([20, 15])

>>> text_removals(s, d)
>>> array([[20,  0,  0, 20, 20],
           [15,  0,  0, 15, 15]])
```

In [151]:
# your code here

Adjust the function to return the total number of points each instructor is removing by adding a True/False argument called `totals`.

E.g.,

```python
s = np.array([True, False, False, True, True])
d = np.array([20, 15])

>>> text_removals(s, d, totals=True)
>>> array([60, 45])
```

In [152]:
# your code here